### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by carla1131** [SistemasTecTlaxiaco/infografia-carla1144#7]
[BAUTISTA_LEON_CARLA_1AS_INFOGRAFIA (1).pdf](https://github.com/SistemasTecTlaxiaco/infografia-carla1144/files/12562408/BAUTISTA_LEON_CARLA_1AS_INFOGRAFIA.1.pdf)

**Comment by DiegoLV117** [comment]
Redacción 8%
Exposición de ideas 11%
Organización de la información 15%
Uso de imágenes 15%
Presentación visual 13%
Referencias 11%
Presentación 13%

Calificación final 17.2
Calificado por Diego Ernesto López Vásquez

**Comment by josealfredo79** [comment]
muy borrosa la imagen por favor mejorarla...favor de mejorarla

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
